export const LOGIN_REQUEST_BEGIN = 'LOGIN_REQUEST_BEGIN';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_ERROR = 'LOGIN_REQUEST_ERROR';
export const RESET_STATE = 'RESET_STATE';

export const FORGOT_PASSWORD_BEGIN = 'FORGOT_PASSWORD_BEGIN';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const CHANGE_PASSWORD_BEGIN = 'CHANGE_PASSWORD_BEGIN';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

export const ADD_PROJECT_BEGIN = 'ADD_PROJECT_BEGIN';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const ADD_PROJECT_ERROR = 'ADD_PROJECT_ERROR';

export const GET_PROJECT_BEGIN = 'GET_PROJECT_BEGIN';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_ERROR = 'GET_PROJECT_ERROR';

export const DELETE_PROJECT_BEGIN = 'DELETE_PROJECT_BEGIN';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR';

export const UPDATE_PROJECT_BEGIN = 'UPDATE_PROJECT_BEGIN';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_ERROR = 'UPDATE_PROJECT_ERROR';

export const UPDATE_PROJECT_STATUS_BEGIN = 'UPDATE_PROJECT_STATUS_BEGIN';
export const UPDATE_PROJECT_STATUS_SUCCESS = 'UPDATE_PROJECT_STATUS_SUCCESS';
export const UPDATE_PROJECT_STATUS_ERROR = 'UPDATE_PROJECT_STATUS_ERROR';

export const GET_COMPANY_BEGIN = 'GET_COMPANY_BEGIN';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_ERROR = 'GET_COMPANY_ERROR';

export const ADD_COMPANY_BEGIN = 'ADD_COMPANY_BEGIN';
export const ADD_COMPANY_SUCCESS = 'ADD_COMPANY_SUCCESS';
export const ADD_COMPANY_ERROR = 'ADD_COMPANY_ERROR';

export const DELETE_COMPANY_BEGIN = 'DELETE_COMPANY_BEGIN';
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS';
export const DELETE_COMPANY_ERROR = 'DELETE_COMPANY_ERROR';

export const UPDATE_COMPANY_BEGIN = 'UPDATE_COMPANY_BEGIN';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';
export const UPDATE_COMPANY_ERROR = 'UPDATE_COMPANY_ERROR';

export const GET_USERS_BEGIN = 'GET_USERS_BEGIN';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const GET_USER_ROLE_BEGIN = 'GET_USER_ROLE_BEGIN';
export const GET_USER_ROLE_SUCCESS = 'GET_USER_ROLE_SUCCESS';
export const GET_USER_ROLE_ERROR = 'GET_USER_ROLE_ERROR';

export const DELETE_USER_BEGIN = 'DELETE_USER_BEGIN';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const ADD_USER_BEGIN = 'ADD_USER_BEGIN';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const GET_ALL_PROJECT_BEGIN = 'GET_ALL_PROJECT_BEGIN';
export const GET_ALL_PROJECT_SUCCESS = 'GET_ALL_PROJECT_SUCCESS';
export const GET_ALL_PROJECT_ERROR = 'GET_ALL_PROJECT_ERROR';

export const GET_TIME_ACTIVITY_BEGIN = 'GET_TIME_ACTIVITY_BEGIN';
export const GET_TIME_ACTIVITY_SUCCESS = 'GET_TIME_ACTIVITY_SUCCESS';
export const GET_TIME_ACTIVITY_ERROR = 'GET_TIME_ACTIVITY_ERROR';

export const FETCH_SCREENSHOT_DATA_REQUEST = 'FETCH_SCREENSHOT_DATA_REQUEST';
export const FETCH_SCREENSHOT_DATA_SUCCESS = 'FETCH_SCREENSHOT_DATA_SUCCESS';
export const FETCH_SCREENSHOT_DATA_FAILURE = 'FETCH_SCREENSHOT_DATA_FAILURE';

export const GET_ALL_USER_BEGIN = 'GET_ALL_USER_BEGIN';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_ERROR = 'GET_ALL_USER_ERROR';

export const GET_TIMELINE_BEGIN = 'GET_TIMELINE_BEGIN';
export const GET_TIMELINE_SUCCESS = 'GET_TIMELINE_SUCCESS';
export const GET_TIMELINE_ERROR = 'GET_TIMELINE_ERROR';

export const FETCH_DSR_DATA_REQUEST = 'FETCH_DSR_DATA_REQUEST';
export const FETCH_DSR_DATA_SUCCESS = 'FETCH_DSR_DATA_SUCCESS';
export const FETCH_DSR_DATA_FAILURE = 'FETCH_DSR_DATA_FAILURE';

export const APPLY_TIME_REQUEST_BEGIN = 'APPLY_TIME_REQUEST_BEGIN';
export const APPLY_TIME_REQUEST_SUCESS = 'APPLY_TIME_REQUEST_SUCESS';
export const APPLY_TIME_REQUEST_FAILURE = 'APPLY_TIME_REQUEST_FAILURE';

export const GET_TIME_REQUEST_BEGIN = 'GET_TIME_REQUEST_BEGIN';
export const GET_TIME_REQUEST_SUCESS = 'GET_TIME_REQUEST_SUCESS';
export const GET_TIME_REQUEST_FAILURE = 'GET_TIME_REQUEST_FAILURE';

export const CHANGE_TIME_REQUEST_STATUS_BEGIN =
  'CHANGE_TIME_REQUEST_STATUS_BEGIN';
export const CHANGE_TIME_REQUEST_STATUS_SUCCESS =
  'CHANGE_TIME_REQUEST_STATUS_SUCCESS';
export const CHANGE_TIME_REQUEST_STATUS_FAILURE =
  'CHANGE_TIME_REQUEST_STATUS_FAILURE';

export const SUBMIT_LEAVE_FORM_REQUEST = 'SUBMIT_LEAVE_FORM_REQUEST';
export const SUBMIT_LEAVE_FORM_SUCCESS = 'SUBMIT_LEAVE_FORM_SUCCESS';
export const SUBMIT_LEAVE_FORM_FAILURE = 'SUBMIT_LEAVE_FORM_FAILURE';

export const FETCH_LEAVE_RECORDS_REQUEST = 'FETCH_LEAVE_RECORDS_REQUEST';
export const FETCH_LEAVE_RECORDS_SUCCESS = 'FETCH_LEAVE_RECORDS_SUCCESS';
export const FETCH_LEAVE_RECORDS_FAILURE = 'FETCH_LEAVE_RECORDS_FAILURE';

export const APPROVE_LEAVE_REQUEST = 'APPROVE_LEAVE_REQUEST';
export const APPROVE_LEAVE_SUCCESS = 'APPROVE_LEAVE_SUCCESS';
export const APPROVE_LEAVE_FAILURE = 'APPROVE_LEAVE_FAILURE';

export const REJECT_LEAVE_REQUEST = 'REJECT_LEAVE_REQUEST';
export const REJECT_LEAVE_SUCCESS = 'REJECT_LEAVE_SUCCESS';
export const REJECT_LEAVE_FAILURE = 'REJECT_LEAVE_FAILURE';

export const CANCEL_LEAVE_REQUEST = 'CANCEL_LEAVE_REQUEST';
export const CANCEL_LEAVE_SUCCESS = 'CANCEL_LEAVE_SUCCESS';
export const CANCEL_LEAVE_FAILURE = 'CANCEL_LEAVE_FAILURE';

export const FETCH_HOLIDAYS_REQUEST = 'FETCH_HOLIDAYS_REQUEST';
export const FETCH_HOLIDAYS_SUCCESS = 'FETCH_HOLIDAYS_SUCCESS';
export const FETCH_HOLIDAYS_FAILURE = 'FETCH_HOLIDAYS_FAILURE';

export const ADD_HOLIDAY_REQUEST = 'ADD_HOLIDAY_REQUEST';
export const ADD_HOLIDAY_SUCCESS = 'ADD_HOLIDAY_SUCCESS';
export const ADD_HOLIDAY_FAILURE = 'ADD_HOLIDAY_FAILURE';

export const EDIT_HOLIDAY_REQUEST = 'EDIT_HOLIDAY_REQUEST';
export const EDIT_HOLIDAY_SUCCESS = 'EDIT_HOLIDAY_SUCCESS';
export const EDIT_HOLIDAY_FAILURE = 'EDIT_HOLIDAY_FAILURE';

export const DELETE_HOLIDAY_REQUEST = 'DELETE_HOLIDAY_REQUEST';
export const DELETE_HOLIDAY_SUCCESS = 'DELETE_HOLIDAY_SUCCESS';
export const DELETE_HOLIDAY_FAILURE = 'DELETE_HOLIDAY_FAILURE';

export const FETCH_COMPOFF_REQUEST = 'FETCH_COMPOFF_REQUEST';
export const FETCH_COMPOFF_SUCCESS = 'FETCH_COMPOFF_SUCCESS';
export const FETCH_COMPOFF_FAILURE = 'FETCH_COMPOFF_FAILURE';

export const APPROVE_COMPOFF_REQUEST = 'APPROVE_COMPOFF_REQUEST';
export const APPROVE_COMPOFF_SUCCESS = 'APPROVE_COMPOFF_SUCCESS';
export const APPROVE_COMPOFF_FAILURE = 'APPROVE_COMPOFF_FAILURE';

export const GET_ATTENDANCE_BEGIN = 'GET_ATTENDANCE_BEGIN_BEGIN';
export const GET_ATTENDANCE_SUCCESS = 'GET_ATTENDANCE_SUCCESS';
export const GET_ATTENDANCE_ERROR = 'GET_ATTENDANCEY_ERROR';

export const FETCH_EXISTING_LEAVE_REQUEST = 'FETCH_EXISTING_LEAVE_REQUEST';
export const FETCH_EXISTING_LEAVE_SUCCESS = 'FETCH_EXISTING_LEAVE_SUCCESS';
export const FETCH_EXISTING_LEAVE_ERROR = 'FETCH_EXISTING_LEAVE_ERROR';

export const GET_LEAVE_HISTORY_REQUEST = 'GET_LEAVE_HISTORY_REQUEST';
export const GET_LEAVE_HISTORY_SUCCESS = 'GET_LEAVE_HISTORY_SUCCESS';
export const GET_LEAVE_HISTORY_ERROR = 'GET_LEAVE_HISTORY_ERROR';

export const ADD_UPDATE_SETTING_REQUEST = 'ADD_UPDATE_SETTING_REQUEST';
export const ADD_UPDATE_SETTING_SUCCESS = 'ADD_UPDATE_SETTING_SUCCESS';
export const ADD_UPDATE_SETTING_ERROR = 'ADD_UPDATE_SETTING_ERROR';

export const GET_SETTING_REQUEST = 'GET_SETTING_REQUEST';
export const GET_SETTING_SUCCESS = 'GET_SETTING_SUCCESS';
export const GET_SETTING_ERROR = 'GET_SETTING_ERROR';

export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
